server:
  port: 8080

database:
  schema: public

spring:
  application:
    name: hoover-service

  jackson:
    default-property-inclusion: non_null

  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: TBD
    username: TBD
    password: TBD
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${database.schema}
        format_sql: true

  liquibase:
    enabled: true
    default-schema: ${database.schema}
    liquibase-schema: ${database.schema}
